data:
  train_files: mertaylin/easyarc-v1-rl@train
  val_files: mertaylin/easyarc-v1-rl@test
  prompt_key: question
  answer_key: answer
  image_key: stacked_train_image
  max_prompt_length: 2048
  max_response_length: 2048
  rollout_batch_size: 256
  shuffle: true
  seed: 1
  max_pixels: 801408
  min_pixels: 262144

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0

worker:
  actor:
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 4
    micro_batch_size_per_device_for_experience: 16
    max_grad_norm: 1.0
    entropy_coeff: 1.0e-3
    use_kl_loss: true
    kl_loss_coef: 1.0e-2
    kl_loss_type: low_var_kl
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: Qwen/Qwen2.5-VL-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    temperature: 1.0
    n: 8
    gpu_memory_utilization: 0.5
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    limit_images: 1

  ref:
    offload:
      offload_params: true

  reward:
    reward_type: function
    compute_score: exactmatch

trainer:
  total_episodes: 500
  logger: ["console", "wandb"]
  project_name: easyarc
  experiment_name: qwenvl7b_easyarcv1
  n_gpus_per_node: 8
  nnodes: 1
  val_freq: 10
  val_before_train: true
  val_only: false
  val_generations_to_log: 10
  save_freq: 5
  remove_previous_ckpt: true
  remove_ckpt_after_load: false
  save_checkpoint_path: /DATA/disk3/mert/models/Qwen2.5-VL-7B-Instruct_EasyArcV1
  load_checkpoint_path: /DATA/disk3/mert/models/Qwen2.5-VL-7B-Instruct_EasyArcV1/global_step_39